// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
    // Achievement & leaderboard Android
    public const string achievement_unlock_25_teams = "CgkIq-LZ2fwaEAIQDQ"; // <GPGSID>
    public const string achievement_play_20_games = "CgkIq-LZ2fwaEAIQAg"; // <GPGSID>
    public const string achievement_international = "CgkIq-LZ2fwaEAIQGg"; // <GPGSID>
    public const string achievement_score_25_goals_in_endless_mode = "CgkIq-LZ2fwaEAIQFg"; // <GPGSID>
    public const string achievement_crazy_cup_champion = "CgkIq-LZ2fwaEAIQGw"; // <GPGSID>
    public const string achievement_score_10_goals = "CgkIq-LZ2fwaEAIQBA"; // <GPGSID>
    public const string achievement_concede_500_goals = "CgkIq-LZ2fwaEAIQEw"; // <GPGSID>
    public const string achievement_lets_play_a_game = "CgkIq-LZ2fwaEAIQAQ"; // <GPGSID>
    public const string achievement_unlock_5_fields = "CgkIq-LZ2fwaEAIQDw"; // <GPGSID>
    public const string achievement_score_100_goals = "CgkIq-LZ2fwaEAIQBQ"; // <GPGSID>
    public const string achievement_unlock_20_balls = "CgkIq-LZ2fwaEAIQCg"; // <GPGSID>
    public const string achievement_unlock_5_teams = "CgkIq-LZ2fwaEAIQCw"; // <GPGSID>
    public const string achievement_unlock_a_field = "CgkIq-LZ2fwaEAIQDg"; // <GPGSID>
    public const string achievement_score_5_goals_in_endless_mode = "CgkIq-LZ2fwaEAIQFA"; // <GPGSID>
    public const string achievement_unlock_10_teams = "CgkIq-LZ2fwaEAIQDA"; // <GPGSID>
    public const string achievement_play_100_games = "CgkIq-LZ2fwaEAIQAw"; // <GPGSID>
    public const string achievement_unlock_10_fields = "CgkIq-LZ2fwaEAIQEA"; // <GPGSID>
    public const string achievement_score_1000_goals = "CgkIq-LZ2fwaEAIQBw"; // <GPGSID>
    public const string achievement_play_7_days = "CgkIq-LZ2fwaEAIQGA"; // <GPGSID>
    public const string achievement_concede_50_goals = "CgkIq-LZ2fwaEAIQEg"; // <GPGSID>
    public const string achievement_champion = "CgkIq-LZ2fwaEAIQGQ"; // <GPGSID>
    public const string leaderboard_best_score = "CgkIq-LZ2fwaEAIQBg"; // <GPGSID>
    public const string achievement_unlock__10_balls = "CgkIq-LZ2fwaEAIQCQ"; // <GPGSID>
    public const string achievement_veteran = "CgkIq-LZ2fwaEAIQFw"; // <GPGSID>
    public const string achievement_unlock_a_ball = "CgkIq-LZ2fwaEAIQCA"; // <GPGSID>
    public const string achievement_concede_10_goals = "CgkIq-LZ2fwaEAIQEQ"; // <GPGSID>
    public const string achievement_score_10_goals_in_endless_mode = "CgkIq-LZ2fwaEAIQFQ"; // <GPGSID>

}

